fixes #1018 allows banners to not contain links
unicef/iogt pull request #1134
Opened 2022-02-08 16:47 UTC by ChrisMarsh82

updated HTML so link would not be added if it didn't exist.
Added logic to add banners if linked page is published or if there is no link

2022-02-08 16:49 UTC, ChrisMarsh82 commented
@ehmadzubair @sheralim012 - can one of you check this is the right way to do the HTML?

2022-02-09 06:15 UTC, sheralim012 requested changes

2022-02-09 06:15 UTC, sheralim012 commented on home/templates/home/tags/banners_list.html
> +        {% if banner.banner_link_page == None %}
`{% if banner.banner_link_page %}` is sufficient

2022-02-09 06:15 UTC, sheralim012 commented on home/templates/home/tags/banners_list.html
> +            <a>{% image banner.banner_image width-360 %}</a>
could you try using span instead of a tag as it shouldn't be clickable without linked page

2022-04-05 18:40 UTC, geoo89 commented
Obsolete due to #1239

2022-04-05 18:40 UTC, closed without merging