IU-20 | add search results per model
unicef/iogt pull request #122
Opened 2021-06-20 13:12 UTC by mikowhy

https://github.com/unicef/iogt/issues/83

2021-06-21 07:27 UTC, mwrobel-merixstudio approved these changes

2021-06-21 07:27 UTC, mwrobel-merixstudio commented on iogt/settings/base.py
> -from django.utils.translation import gettext_lazy as _
ok. I see - it was duplicated ;)

2021-06-25 07:12 UTC, mwrobel-merixstudio approved these changes

2021-07-05 11:01 UTC, mwardak-mrx requested changes
Some minor changes and it's good :)

2021-07-05 16:34 UTC, dannyparsons commented
merged in #222

2021-07-05 16:34 UTC, closed without merging

2021-07-06 07:41 UTC, mikowhy commented
@ehmadzubair please let me know if unmerged commits (https://github.com/unicef/iogt/pull/122/files) should be committed as well

2021-07-06 08:25 UTC, mikowhy commented on search/views.py
> +        search_results_no = 0
changed

2021-07-06 08:27 UTC, mikowhy commented on search/views.py
> +    page = request.GET.get("page", 1)
changed

2021-07-06 08:37 UTC, mikowhy commented
unmerged commits in new PR -> https://github.com/unicef/iogt/pull/237

2021-07-06 09:00 UTC, mwardak-mrx commented on search/views.py
> +    page = request.GET.get("page", 1)
Ah, right, I missed the fact that this is a function view and not a class-based DRF view. It's fine then 👍