adds site version
unicef/iogt pull request #1281
Opened 2022-05-13 09:27 UTC by sheralim012

Closes #911 

- adds site version

2022-05-18 16:44 UTC, istride requested changes

2022-05-19 13:49 UTC, sheralim012 commented on iogt/templates/wagtailadmin/shared/menu_settings_menu_item.html
> +    <p class="nav-submenu__footer">Site v.{% site_version %}</p>
done

2022-05-19 13:49 UTC, sheralim012 commented on iogt/settings/base.py
> +SITE_VERSION = os.getenv('SITE_VERSION')
done

2022-05-19 20:10 UTC, istride approved these changes

2022-05-19 20:12 UTC, merged