Adding selenium tests
unicef/iogt pull request #1334
Opened 2022-07-19 14:04 UTC by edmoss345

2022-07-29 18:42 UTC, edmoss345 commented
@istride could you review and merge this. Still plenty more to be done on the testing front, but this PR contains some initial tests and examples which should help others if they are coming to write selenium tests. 

Have created a backlog of tests to be added in #1349 , so would like to get this PR merged then next week I will do smaller PRs related to individual groups of tests.

2022-08-03 09:01 UTC, istride requested changes
I suggest reducing the number of directories by merging 'questionnaires_common' and 'survey' into one 'questionnaires' directory.

2022-08-05 03:37 UTC, edmoss345 commented on home/factories.py
> +class SurveyFactory(PageFactory):
Have pointed to the factory in questionnaires app

2022-08-05 03:38 UTC, edmoss345 commented on selenium_tests/questionnaires_common/test_questionnaire_inputs.py
> +class QInputsSeleniumTests(BaseSeleniumTests):
have changed

2022-08-05 03:38 UTC, edmoss345 commented on selenium_tests/TestBase/base.py
> +class BaseSeleniumTests(LiveServerTestCase):
have just implemented 'selenium_tests/base.py' for simplicity

2022-08-05 03:39 UTC, edmoss345 commented on selenium_tests/example_test/tests.py
> +class ExampleSeleniumTests(BaseSeleniumTests):
Have removed and updated readme

2022-08-05 03:39 UTC, edmoss345 commented on selenium_tests/homepage/test_login.py
> +        assert self.user.username in body_text
Have changed, only used this once so far but will bear in mind when writing future tests

2022-08-05 03:42 UTC, edmoss345 commented
@istride have made the changes as requested, hopefully this is ready to merge. I also took out one of the tests from this PR as it was only partially written so no sense having it in here at this point.

2022-08-16 13:09 UTC, istride approved these changes

2022-08-16 13:10 UTC, merged