gracefully handle change of clean name
unicef/iogt pull request #1389
Opened 2022-09-05 06:26 UTC by sheralim012

2022-09-07 17:08 UTC, istride requested changes
In general, I find these tests very hard to read and follow. There should be an effort to improve test code in the same way that regular application code should be improved too. One suggestion would be to write smaller, more focused tests, which should be simpler.

2022-09-07 18:58 UTC, sheralim012 commented on questionnaires/tests.py
> +        skip_logic = json.dumps(
done

2022-09-07 19:11 UTC, sheralim012 commented on questionnaires/tests.py
> +            f'{self.user_submission_01.id},{self.poll.title},{self.user_submission_01.submit_time},User,{self.user_01.username}\r\n' \
submission id by database, questionnaire title and username by factory boy sequence generator, questionnaire URL by wagtail, and datetime from django timezone util all are dynamically generated

I think for questionnaire title, username, and datetime we can specify literal while creating and then use the same literal for assertions

but for submission id and questionnaire URL object should be used as these are out of our control

2022-09-07 19:44 UTC, sheralim012 commented on questionnaires/tests.py
> +            f'{self.user_submission_01.id},{self.poll.title},{self.user_submission_01.submit_time},User,{self.user_01.username}\r\n' \
done

2022-09-09 09:48 UTC, istride approved these changes

2022-09-09 09:49 UTC, merged