Questionnaire field type "Drop down" defaults to the blank option
unicef/iogt pull request #1459
Opened 2022-11-09 06:14 UTC by Alihassanc5

Closes #1457 
- Questionnaire field type "Drop down" defaults to the blank option.
- Blank option is selectable.
- For required fields, user should be required to give a response that is NOT blank.

![image](https://user-images.githubusercontent.com/62539376/200753540-d3d08a51-f727-434a-8ff2-4ae759613136.png)

2023-01-17 17:13 UTC, istride requested changes
Please resolve conflicts.

2023-01-17 17:13 UTC, istride commented on questionnaires/tests.py
> +        default_drop_down_option = parsed_response.find('div', {'class': 'quest-item'}).find('select').find('option').text
I have a feeling that searching HTML markup like this is going to be harder to maintain as the number of tests increases. Beautiful Soup supports [CSS selectors](https://beautiful-soup-4.readthedocs.io/en/latest/#css-selectors), which may be more manageable.

The Selenium tests also use locators, so perhaps there is a way to share these locators across the test suite.

2023-01-19 09:47 UTC, Alihassanc5 commented on questionnaires/tests.py
> +        Site.objects.all().delete()
Fixed it by simple approach.

2023-01-19 09:47 UTC, Alihassanc5 commented on questionnaires/tests.py
> +        self.home_page = self.site.root_page
Fixed it.

2023-01-19 09:47 UTC, Alihassanc5 commented on questionnaires/models.py
> +            for answer_ in answer:
Fixed it!

2023-03-08 16:56 UTC, istride approved these changes
Please merge if the f-string issue is ok.

2023-03-08 16:56 UTC, istride commented on questionnaires/tests.py
> +        response = self.client.post(self.poll.url, {f'{poll_question.clean_name}': 'c1'})
is this supposed to be an f-string?

2023-03-09 07:48 UTC, sheralim012 commented on questionnaires/tests.py
> +        response = self.client.post(self.poll.url, {f'{poll_question.clean_name}': 'c1'})
No, updated it.

2023-03-09 07:57 UTC, merged