Adds user activity tracking via Matomo
unicef/iogt pull request #1579
Opened 2023-03-15 13:09 UTC by Alihassanc5

Closes #1566

2023-03-16 05:55 UTC, sheralim012 requested changes

2023-03-16 05:55 UTC, sheralim012 commented on requirements.dev.txt
> +django-matomo
Specify version

2023-03-17 00:18 UTC, cbunicef commented
Would it be possible to separately specify URLs for global and local Matomo tracking?

2023-03-17 10:41 UTC, sheralim012 commented
> Would it be possible to separately specify URLs for global and local Matomo tracking?

It's doable but what's the use case behind this?

2023-03-18 13:33 UTC, cbunicef commented
> > Would it be possible to separately specify URLs for global and local Matomo tracking?
> 
> It's doable but what's the use case behind this?

For example, if we have an IoGT platform deployed by a UNICEF partner on their servers. They might use Matomo (local, cloud etc) to track locally, and we might want to use our global Matomo to also track globally.

We never needed to consider multiple systems for Google Analytics because there was only one system available, but since local deployments are possible with Matomo it would be something I could see us using.

This isn't urgent, but it seemed that since the team was currently working on this PR it would be faster now than digging into it again at a later date.

2023-03-20 18:36 UTC, sheralim012 requested changes

2023-03-22 12:43 UTC, cbunicef commented
Please add a feature flag for this, while it's in development.

2023-04-11 12:00 UTC, istride requested changes

2023-04-11 12:00 UTC, istride commented on requirements.dev.txt
> +django-matomo==0.1.6
django-matomo cannot be a dev-only dependency

2023-04-12 08:35 UTC, istride approved these changes

2023-04-12 11:08 UTC, merged