Interactive Game Developed Version.
unicef/iogt pull request #1705
Opened 2024-07-10 09:05 UTC by mizanriseup

This is a pull request to check and merge the code for interactive game with IOGT.

2024-07-10 13:29 UTC, istride requested changes
I think this should be cleaned up a bit more to remove redundant comments, commented code and redundant imports. I suggest also that you run the [black](https://black.readthedocs.io/en/stable/index.html) code formatter over this.

2024-07-10 13:29 UTC, istride commented on interactive/models.py
> +# from interactive.services import ShortCodeService
Commented code.

2024-07-10 13:29 UTC, istride commented on interactive/models.py
> +    # button_text = models.CharField(max_length=255)
commented code.

2024-07-10 13:29 UTC, istride commented on interactive/models.py
> +        # FieldPanel('button_text'),
commented code.

2024-07-14 07:22 UTC, mizanriseup commented on interactive/admin.py
> +from django.contrib import admin
Updated.

2024-07-14 07:24 UTC, mizanriseup commented on interactive/api/views.py
> +        # Extract validated data from serializer
Updated

2024-07-14 07:24 UTC, mizanriseup commented on interactive/models.py
> +# from interactive.services import ShortCodeService
Updated.

2024-07-14 07:24 UTC, mizanriseup commented on interactive/models.py
> +    # button_text = models.CharField(max_length=255)
Updated

2024-07-14 07:24 UTC, mizanriseup commented on interactive/models.py
> +        # FieldPanel('button_text'),
Updated

2024-07-15 15:05 UTC, istride approved these changes

2024-07-15 15:09 UTC, merged