Add admin urls in migration report.
unicef/iogt pull request #751
Opened 2021-10-29 14:59 UTC by geoo89

Regular page URLs don't work when a page is in draft state.

2021-11-02 07:17 UTC, ehmadzubair requested changes

2021-11-02 07:17 UTC, ehmadzubair commented on iogt_content_migration/management/commands/load_v1_db.py
> +                            f'title: {translated_section.title}. URL: {translated_section.full_url}. Admin URL: http://localhost/admin/pages/{translated_section.id}/edit/')
I think we should use the reverse URL function to generate this. That will also help make the domain dynamic.

2021-11-02 10:15 UTC, geoo89 commented
Feel free to make a separate PR and close this one.

On Tue, Nov 2, 2021, 07:18 Ehmad Zubair ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In iogt_content_migration/management/commands/load_v1_db.py
> <https://github.com/unicef/iogt/pull/751#discussion_r740771716>:
>
> > @@ -439,7 +439,7 @@ def migrate_sections(self):
>                      })
>                      if row['description'] is None:
>                          self.post_migration_report_messages['sections_with_null_description'].append(
> -                            f'title: {translated_section.title}. URL: {translated_section.full_url}.')
> +                            f'title: {translated_section.title}. URL: {translated_section.full_url}. Admin URL: http://localhost/admin/pages/{translated_section.id}/edit/')
>
> I think we should use the reverse URL function to generate this. That will
> also help make the domain dynamic.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/unicef/iogt/pull/751#pullrequestreview-794945507>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFFSNYTYO7RORMYMGOG7I3UJ6GCTANCNFSM5G7Q5GDA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-10 10:39 UTC, geoo89 commented
Obsolete due to #790

2021-11-10 10:39 UTC, closed without merging