added locale to home page title
unicef/iogt pull request #767
Opened 2021-11-02 18:42 UTC by mbilalhameed

fixes #611

2021-11-02 18:43 UTC, mbilalhameed commented
@sheralim012

2021-11-03 09:44 UTC, sheralim012 requested changes

2021-11-03 09:44 UTC, sheralim012 commented on iogt_content_migration/management/commands/load_v1_db.py
> +            translated_home_page.title = home_page.title + ' [' + locale.__str__() + ']'
use f-string

2021-11-03 09:44 UTC, sheralim012 commented on iogt_content_migration/management/commands/load_v1_db.py
> +            translated_home_page.title = home_page.title + ' [' + locale.__str__() + ']'
update draft title too

2021-11-03 09:44 UTC, sheralim012 commented on iogt_content_migration/management/commands/load_v1_db.py
> +    def add_home_page_title_and_locale(self, home_page, locale):
simplify this no need to create method

2021-11-03 18:57 UTC, sheralim012 requested changes

2021-11-03 18:57 UTC, sheralim012 commented on iogt_content_migration/management/commands/load_v1_db.py
> +                modified_title = f"{home.title} [{locale.__str__()}]"
use `translated_home_page.title` instead of `home.title`

2021-11-04 06:45 UTC, sheralim012 approved these changes

2021-11-08 21:12 UTC, merged