refactor templates
unicef/iogt pull request #768
Opened 2021-11-02 20:07 UTC by sheralim012

2021-11-03 10:22 UTC, ehmadzubair commented on home/templates/home/tags/banners_list.html
> +            <img src="{{ banner_img.url }}" alt="{{ banner_img.alt }}">
maybe remove it

2021-11-03 10:40 UTC, ehmadzubair requested changes

2021-11-03 10:40 UTC, ehmadzubair commented on home/templates/home/tags/featured_content_card.html
> +<svg width="18" height="16" viewBox="0 0 18 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Any idea why this is hardcoded?

2021-11-03 10:40 UTC, ehmadzubair commented on home/templates/home/tags/featured_content_card.html
> +{% include 'home/tags/right_angle_bracket.html' %}
Make this a templatetag

2021-11-22 12:55 UTC, geoo89 commented
- The `LARGER IMAGE FOR TOP PAGE IN LIST AS IN V1` flag is not respected: In sections, the top article is always displayed with a larger image.
- PageLinkPages don't show in sections
- Questionnaire links don't use a section's color scheme
    - Subsections: Should they use the section's color scheme as well? Only implement if trivial. We might have to check back with Chris and revisit the coloring schemes as having everything in the section color scheme might be too intrusive.
- Adding featured content crashes a section:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/en/sections/covid-19/

Django Version: 3.1.11
Python Version: 3.6.9
Installed Applications:
['home',
 'search',
 'iogt_users',
 'comments',
 'iogt_content_migration',
 'questionnaires',
 'messaging',
 'django.contrib.humanize',
 'wagtail_localize',
 'wagtail_localize.locales',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.modeladmin',
 'wagtailmenus',
 'wagtailmedia',
 'wagtailmarkdown',
 'wagtail_transfer',
 'wagtailsvg',
 'wagtail.contrib.settings',
 'django_comments_xtd',
 'django_comments',
 'modelcluster',
 'taggit',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'sass_processor',
 'translation_manager',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'iogt_users.middlewares.RegistrationSurveyRedirectMiddleware',
 'external_links.middleware.RewriteExternalLinksMiddleware',
 'iogt.middleware.CacheControlMiddleware']


Template error:
In template /data/idems/iogt/iogt/home/templates/home/tags/featured_content_card.html, error at line 4
   21
   1 : {% load image_tags %}
   2 : {% load static wagtailcore_tags wagtailimages_tags %}
   3 : 
   4 :  {% render_png_from_svg page.get_icon_url width=16 height=16 %} 
   5 : <a href="{% pageurl page %}">{{ page.title }}</a>
   6 : {% include 'home/tags/angle_bracket.html' %}

Traceback (most recent call last):
  File "/data/idems/iogt/iogt/home/models.py", line 1010, in get_png_image
    obj = cls.objects.get(svg_path=svg_path, fill_color=fill_color, stroke_color=stroke_color)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name

During handling of the above exception (SVGToPNGMap matching query does not exist.), another exception occurred:
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", li [...]

2021-11-24 08:55 UTC, sheralim012 commented
@geoo89 changes addressed

2021-11-25 20:03 UTC, geoo89 commented
Index page description isn't displayed for articles.

2021-11-26 05:55 UTC, sheralim012 commented
pushed a fix for index page description for articles

2021-11-29 14:42 UTC, geoo89 commented
The section color and background color should not affect the text/background of the elements of a section.

More sophisticated coloring rules to be determined later.

2021-11-30 07:12 UTC, sheralim012 commented
@geoo89 changes addressed

2021-11-30 13:28 UTC, merged