Recreate registration survey during migration
unicef/iogt pull request #783
Opened 2021-11-08 12:25 UTC by ehmadzubair

2021-11-16 12:34 UTC, ehmadzubair commented
@geoo89 I'm seeing the following missing translations in the post migration report for the registration survey:

```
===> REGISTRATION SURVEY TRANSLATION NOT FOUND
Translation not found for label: dob in locale: Ndebele
Translation not found for label: gender in locale: Ndebele
Translation not found for label: location in locale: Ndebele
Translation not found for label: mobile_number in locale: Ndebele
Translation not found for label: education_level in locale: Ndebele
Translation not found for label: email_address in locale: Ndebele
Translation not found for label: dob in locale: Chichewa
Translation not found for label: gender in locale: Chichewa
Translation not found for label: location in locale: Chichewa
Translation not found for label: mobile_number in locale: Chichewa
Translation not found for label: education_level in locale: Chichewa
Translation not found for label: email_address in locale: Chichewa
Translation not found for label: dob in locale: Shona
Translation not found for label: gender in locale: Shona
Translation not found for label: location in locale: Shona
Translation not found for label: mobile_number in locale: Shona
Translation not found for label: education_level in locale: Shona
Translation not found for label: email_address in locale: Shona
Translation not found for label: dob in locale: ta
Translation not found for label: gender in locale: ta
Translation not found for label: location in locale: ta
Translation not found for label: mobile_number in locale: ta
Translation not found for label: education_level in locale: ta
Translation not found for label: email_address in locale: ta

```

2021-11-17 05:39 UTC, sheralim012 requested changes

2021-11-17 05:39 UTC, sheralim012 commented on iogt_content_migration/management/commands/load_v1_db.py
> +            title='Registration Survey', live=True, allow_multiple_submissions=False, submit_button_text='Register')
add allow_anonymouse_submission=False

2021-11-17 11:26 UTC, geoo89 commented
This appears to crash for global:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/data/idems/iogt/iogt/iogt_content_migration/management/commands/load_v1_db.py", line 100, in handle
    self.migrate(root)
  File "/data/idems/iogt/iogt/iogt_content_migration/management/commands/load_v1_db.py", line 190, in migrate
    self.migrate_post_registration_survey()
  File "/data/idems/iogt/iogt/iogt_content_migration/management/commands/load_v1_db.py", line 1781, in migrate_post_registration_survey
    field = SurveyFormField.objects.get(page=translated_survey, admin_label=admin_label)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
questionnaires.models.DoesNotExist: SurveyFormField matching query does not exist.
```

2021-11-17 11:36 UTC, geoo89 commented on iogt_content_migration/management/commands/load_v1_users.py
> +                    'select_date_of_birth': row['date_of_birth'],
Shouldn't these match the admin labels (i.e. the same keys as in row)?

2021-11-19 12:34 UTC, merged