Fix - Group Permission Restriction
unicef/iogt pull request #79
Opened 2021-05-28 05:54 UTC by ehmadzubair

Fixes #78 

We'll still need to add a template for this 403 page to look 'decent'. Not spending time on it right now.

2021-06-02 13:27 UTC, istride commented
@ehmadzubair my understanding is that you will be adding some test cases to this PR

2021-06-02 13:29 UTC, ehmadzubair commented
Yes, that is correct. Right after I complete comments

2021-06-07 13:38 UTC, ehmadzubair commented
@istride I have updated this PR with the Test Cases

2021-06-07 13:41 UTC, ehmadzubair commented on iogt/templates/header.html
> +                <img src="{% static "images/iogt-logo-two-lines.png" %}"/>
This was causing the test suite to not run.

2021-06-09 06:31 UTC, ehmadzubair commented
@isedwards If you can review/merge this please.

2021-06-14 12:08 UTC, istride requested changes
@ehmadzubair would you add some instructions to the README about how to run the tests. Perhaps add a target to the Makefile.

I'm having trouble running the tests. Firstly, some issue with static files, for which, I ran `./manage.py collectstatic` to resolve. Secondly, I have an issue with the Django Debug Toolbar, which I have not found a fix for, as follows:

```
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
```

2021-06-14 14:24 UTC, ehmadzubair commented
@istride I've added separate settings for running tests and both the issues have been resolved (not snoozed). I've also added the readme steps to run the tests

2021-06-15 08:50 UTC, istride approved these changes

2021-06-15 08:57 UTC, merged